import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const inter = Poppins({subsets: ["latin-ext"], weight: ['400', '500', '600', '700']});

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-transparent backdrop-blur-[20px] h-[100vh]">
          {children}
        </div>
      </body>
    </html>
  );
}
